require.config({
    baseUrl: "",
    urlArgs: 'ver=' + (+new Date()),
    waitSeconds: 0,
    paths: {
        'app': 'scripts/app',
        'util': 'scripts/util',
        'config': 'scripts/config',
        'angular': 'vender/angular-1.2.28/angular.min',
        'angular-ui-router': 'scripts/angular-ui-router',
        'angularAMD': 'scripts/angularAMD',
        'ngAnimate': 'vender/angular-1.2.28/angular-animate.min',
        'jquery': 'vender/jquery/jquery-1.9.1.min',
        'ui-bootstrap': 'scripts/ui-bootstrap-tpls-0.11.0',
        'angular-sanitize': 'vender/angular-1.2.28/angular-sanitize',
        'blockUI': 'scripts/angular-block-ui.min',
        'highstock': 'scripts/highstock.src',
        'highcharts-ng': 'scripts/highcharts-ng',
        'funnel': 'scripts/funnel',
        'chart': 'scripts/services/chart',
        'directives': 'scripts/directives/directives',
        'filters': 'scripts/filter/filters',
        'dataToChartConfig': 'scripts/services/dataToChartConfig',
        'ajaxService': 'scripts/services/ajaxServices',
        'projectHouseListService': 'scripts/services/projectHouseListService',
        'toastr': 'scripts/angular-toastr.min',
        'upload': 'vender/ngFileUpload/ng-file-upload.min',
        'salesQuery': 'scripts/services/salesQuery',
        'widget': 'scripts/widget',
        'window': 'scripts/window',
        'slider': 'vender/angular-1.2.28/slider',
        'WdatePicker': 'vender/My97DatePicker/WdatePicker',


        'labelNetworkServices': 'views/labelNetwork/labelNetworkServices',
        'labelLocalServices': 'views/labelLocal/labelLocalServices',
        'customerClassifyServices': 'views/marketing/customerClassify/customerClassifyServices',
        'investmentCustomerServices': 'views/marketing/investmentCustomer/investmentCustomerServices',
        'directedServices': 'views/marketing/directed/directedServices',
        'ownerTypeServices': 'views/report/customer/ownerType/ownerTypeServices',
        'turnoverCustomerServices': 'views/report/customer/turnoverCustomer/turnoverCustomerServices',
        'repeatBuyServices': 'views/report/customer/repeatBuy/repeatBuyServices',
        'turnoverProductServices': 'views/report/product/turnoverProduct/turnoverProductServices',
        'salesAnalysisServices': 'views/report/format/salesAnalysis/salesAnalysisServices',

        'dashboardSalesServices': 'views/dashboard/sales/dashboardSalesServices',
        'dashboardCustomerServices': 'views/dashboard/customer/dashboardCustomerServices',
        'dashboardPurchasServices': 'views/dashboard/purchas/dashboardPurchasServices',


        'projectShowServices': 'views/projectShow/projectShowServices',
        'clientShowServices': 'views/clientShow/clientShowServices',
        'clientSearchServices': 'views/clientSearch/clientSearchServices',
        'clientBatchSearchServices': 'views/clientBatchSearch/clientBatchSearchServices',
        'signinServices': 'views/signin/signinServices'

    },
    shim: {
        'toastr': ['angular'],
        'upload': ['angular'],
        'angular-ui-router': ['angular'],
        'slider': ['angular', 'jquery'],
        'angular': ['jquery'],
        'util': ['angular'],
        'angularAMD': ['angular'],
        'ngAnimate': ['angular'],
        'ui-bootstrap': ['angular'],
        'angular-sanitize': ['angular'],
        'blockUI': ['angular'],
        'chart': ['angular'],
        'directives': ['angular'],
        'filters': ['angular'],
        'dataToChartConfig': ['angular'],
        'highstock': ['jquery'],
        'highcharts-ng': ['highstock'],
        'funnel': 'highstock'
    },
    deps: ['app']
});