package com.sxit.model.pmp;

public class RptZyFormatConvert{
	

		private String index_flow_id;//   	private String proj_id;//   	private String index_format_type;//   	private Integer buy_cst_num;//   	private Integer buy_cst_deal_num;//   	private Integer rent_cst_num;//   	private Integer rent_cst_deal_num;//   	private Integer tj_cst_num;//   	private Integer tj_cst_deal_num;//   	private Integer dk_cst_num;//   	private Integer dk_cst_deal_num;//   	private Integer Tj_rent_cst_num;//   	private Integer Tj_rent_cst_deal_num;//   	private Integer dk_rent_cst_num;//   	private Integer dk_rent_cst_deal_num;//
	private java.sql.Timestamp create_time;// 
	public java.sql.Timestamp getCreate_time() {
	    return this.create_time;
	}
	public void setCreate_time(java.sql.Timestamp create_time) {
	    this.create_time=create_time;
	}	public String getIndex_flow_id() {	    return this.index_flow_id;	}	public void setIndex_flow_id(String index_flow_id) {	    this.index_flow_id=index_flow_id;	}	public String getProj_id() {	    return this.proj_id;	}	public void setProj_id(String proj_id) {	    this.proj_id=proj_id;	}	public String getIndex_format_type() {	    return this.index_format_type;	}	public void setIndex_format_type(String index_format_type) {	    this.index_format_type=index_format_type;	}	public Integer getBuy_cst_num() {	    return this.buy_cst_num;	}	public void setBuy_cst_num(Integer buy_cst_num) {	    this.buy_cst_num=buy_cst_num;	}	public Integer getBuy_cst_deal_num() {	    return this.buy_cst_deal_num;	}	public void setBuy_cst_deal_num(Integer buy_cst_deal_num) {	    this.buy_cst_deal_num=buy_cst_deal_num;	}	public Integer getRent_cst_num() {	    return this.rent_cst_num;	}	public void setRent_cst_num(Integer rent_cst_num) {	    this.rent_cst_num=rent_cst_num;	}	public Integer getRent_cst_deal_num() {	    return this.rent_cst_deal_num;	}	public void setRent_cst_deal_num(Integer rent_cst_deal_num) {	    this.rent_cst_deal_num=rent_cst_deal_num;	}	public Integer getTj_cst_num() {	    return this.tj_cst_num;	}	public void setTj_cst_num(Integer tj_cst_num) {	    this.tj_cst_num=tj_cst_num;	}	public Integer getTj_cst_deal_num() {	    return this.tj_cst_deal_num;	}	public void setTj_cst_deal_num(Integer tj_cst_deal_num) {	    this.tj_cst_deal_num=tj_cst_deal_num;	}	public Integer getDk_cst_num() {	    return this.dk_cst_num;	}	public void setDk_cst_num(Integer dk_cst_num) {	    this.dk_cst_num=dk_cst_num;	}	public Integer getDk_cst_deal_num() {	    return this.dk_cst_deal_num;	}	public void setDk_cst_deal_num(Integer dk_cst_deal_num) {	    this.dk_cst_deal_num=dk_cst_deal_num;	}	public Integer getTj_rent_cst_num() {	    return this.Tj_rent_cst_num;	}	public void setTj_rent_cst_num(Integer Tj_rent_cst_num) {	    this.Tj_rent_cst_num=Tj_rent_cst_num;	}	public Integer getTj_rent_cst_deal_num() {	    return this.Tj_rent_cst_deal_num;	}	public void setTj_rent_cst_deal_num(Integer Tj_rent_cst_deal_num) {	    this.Tj_rent_cst_deal_num=Tj_rent_cst_deal_num;	}	public Integer getDk_rent_cst_num() {	    return this.dk_rent_cst_num;	}	public void setDk_rent_cst_num(Integer dk_rent_cst_num) {	    this.dk_rent_cst_num=dk_rent_cst_num;	}	public Integer getDk_rent_cst_deal_num() {	    return this.dk_rent_cst_deal_num;	}	public void setDk_rent_cst_deal_num(Integer dk_rent_cst_deal_num) {	    this.dk_rent_cst_deal_num=dk_rent_cst_deal_num;	}
	
}
