package com.sxit.mgt.pmp.dto;


public class RptProjBusinessModel{
	
		private Long proj_business_id; 	private Integer proj_abuilding;	private Integer proj_abuilding_set; 	private Integer proj_presell;	private Integer proj_presell_set;  	private Integer proj_onsell;  	private Integer proj_onsell_set;  	private Integer proj_presell_counts;	private Integer proj_onsell_counts;  	private Integer proj_deal01;	private Integer proj_deal02;	private Integer proj_deal03;	private Integer proj_deal04;  	private Integer proj_set01;  	private Integer proj_set02;  	private double proj_rate;   	private java.sql.Timestamp create_time;
	private Integer proj_number;	public Integer getProj_number() {
		return proj_number;
	}
	public void setProj_number(Integer proj_number) {
		this.proj_number = proj_number;
	}
	public Long getProj_business_id() {	    return this.proj_business_id;	}	public void setProj_business_id(Long proj_business_id) {	    this.proj_business_id=proj_business_id;	}	public Integer getProj_abuilding() {	    return this.proj_abuilding;	}	public void setProj_abuilding(Integer proj_abuilding) {	    this.proj_abuilding=proj_abuilding;	}	public Integer getProj_abuilding_set() {	    return this.proj_abuilding_set;	}	public void setProj_abuilding_set(Integer proj_abuilding_set) {	    this.proj_abuilding_set=proj_abuilding_set;	}	public Integer getProj_presell() {	    return this.proj_presell;	}	public void setProj_presell(Integer proj_presell) {	    this.proj_presell=proj_presell;	}	public Integer getProj_presell_set() {	    return this.proj_presell_set;	}	public void setProj_presell_set(Integer proj_presell_set) {	    this.proj_presell_set=proj_presell_set;	}	public Integer getProj_onsell() {	    return this.proj_onsell;	}	public void setProj_onsell(Integer proj_onsell) {	    this.proj_onsell=proj_onsell;	}	public Integer getProj_onsell_set() {	    return this.proj_onsell_set;	}	public void setProj_onsell_set(Integer proj_onsell_set) {	    this.proj_onsell_set=proj_onsell_set;	}	public Integer getProj_presell_counts() {	    return this.proj_presell_counts;	}	public void setProj_presell_counts(Integer proj_presell_counts) {	    this.proj_presell_counts=proj_presell_counts;	}	public Integer getProj_onsell_counts() {	    return this.proj_onsell_counts;	}	public void setProj_onsell_counts(Integer proj_onsell_counts) {	    this.proj_onsell_counts=proj_onsell_counts;	}	public Integer getProj_deal01() {	    return this.proj_deal01;	}	public void setProj_deal01(Integer proj_deal01) {	    this.proj_deal01=proj_deal01;	}	public Integer getProj_deal02() {	    return this.proj_deal02;	}	public void setProj_deal02(Integer proj_deal02) {	    this.proj_deal02=proj_deal02;	}	public Integer getProj_deal03() {	    return this.proj_deal03;	}	public void setProj_deal03(Integer proj_deal03) {	    this.proj_deal03=proj_deal03;	}	public Integer getProj_deal04() {	    return this.proj_deal04;	}	public void setProj_deal04(Integer proj_deal04) {	    this.proj_deal04=proj_deal04;	}	public Integer getProj_set01() {	    return this.proj_set01;	}	public void setProj_set01(Integer proj_set01) {	    this.proj_set01=proj_set01;	}	public Integer getProj_set02() {	    return this.proj_set02;	}	public void setProj_set02(Integer proj_set02) {	    this.proj_set02=proj_set02;	}	public double getProj_rate() {	    return this.proj_rate;	}	public void setProj_rate(double proj_rate) {	    this.proj_rate=proj_rate;	}	public java.sql.Timestamp getCreate_time() {	    return this.create_time;	}	public void setCreate_time(java.sql.Timestamp create_time) {	    this.create_time=create_time;	}
}
